AWSTemplateFormatVersion: 2010-09-09
Resources:
  myLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: "FormationTemplate"
      LaunchTemplateData:
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            SecurityGroupIds:
              - !GetAtt MyTempSecGrp.GroupId
            DeleteOnTermination: true
        Placement:
          Tenancy: dedicated
        ImageId: ami-04f1014c8adcfa670
        InstanceType: t2.micro
        KeyName: AwsDemoKey