---
AWSTemplateFormatVersion : "2010-09-09"

Description: >
  My
  first
  template.

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04f1014c8adcfa670
      KeyName: AwsDemoKey
      SecurityGroupIds:
       - !GetAtt MySecGrp.GroupId
      UserData: !Base64 |
          #!bin/bash
          yum update
          yum install nginx -y
          systemctl start nginx
          systemctl enable nginx



  MySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "MyDemoSecGrp"
      GroupDescription: "WebServer Sec Grp"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
