---
AWSTemplateFormatVersion : "2010-09-09"

Description: >
  My
  first
  template.

Resources:

  MyLBSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "MyLBSecGrp"
      GroupDescription: "Load balancer Sec Grp"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyTempSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "MyTempSecGrp"
      GroupDescription: "Template sec grp"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !GetAtt MyLBSecGrp.GroupId

  MyDatabaseSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "MyDatabaseSecGrp"
      GroupDescription: "Template sec grp"
      SecurityGroupIngress:
      - IpProtocol: "tcp"
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: "tcp"
        FromPort: 80
        ToPort: 80
        

  MyLaunchTemplate:
      Type: 'AWS::EC2::LaunchTemplate'
      Properties:
        LaunchTemplateName: "FormationTemplate"
        LaunchTemplateData: 
          NetworkInterfaces:
            - DeviceIndex: 0
              AssociatePublicIpAddress: true
              Groups:
                - !GetAtt MyTempSecGrp.GroupId
              DeleteOnTermination: true
          ImageId: ami-04f1014c8adcfa670
          InstanceType: t2.micro
          KeyName: AwsDemoKey
  
  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: MyTargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: vpc-0e0102b7d2a6442bb
      TargetType: instance
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /health-check
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP

  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: "MyLB"
      Scheme: internet-facing
      SecurityGroups: 
        - !GetAtt MyLBSecGrp.GroupId
      SubnetMappings: 
        - SubnetId: subnet-0eb075e9f84c19e8d
        - SubnetId: subnet-0373ffc28a383518f
        - SubnetId: subnet-03bfaf7e959364fbf

  MyListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: MyAutoScalingGroup
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 1
      DesiredCapacity: 1
      TargetGroupARNs:
        - !Ref MyTargetGroup
      VPCZoneIdentifier:
          - subnet-0eb075e9f84c19e8d
          - subnet-0373ffc28a383518f
          - subnet-03bfaf7e959364fbf

  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: mydbsubnetgroup
      DBSubnetGroupDescription: "My DB subnet group"
      SubnetIds:
        - subnet-0eb075e9f84c19e8d
        - subnet-0373ffc28a383518f
        - subnet-03bfaf7e959364fbf

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: MyDBInstance
      DBInstanceClass: db.t2.micro
      Engine: mariadb
      EngineVersion: "10.6.10"
      MasterUsername: admin
      MasterUserPassword: password
      AllocatedStorage: 20
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      VPCSecurityGroups:
        - !GetAtt MyTempSecGrp.GroupId  
        
  MyEfsFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: MyEfsFileSystem
      ThroughputMode: bursting
      BackupPolicy:
        Status: ENABLED